AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # Lambda Functions
  TestLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test_lambda
      Handler: test_lambda.lambda_handler
      Runtime: python2.7
      Description: just a test lambda
      Timeout: 15
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Linear10PercentEvery2Minutes
        Alarms:
          # A list of alarms that you want to monitor. Automatic rollback if the alarms are detected.
          - !Ref TestLambdaErrorAlarm
          # - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
      Environment:
        Variables: 
          PLATFORM_ARN_DEV : arn:aws:sns:!Ref "AWS::Region":!Ref "AWS::AccountId":app/APNS_SANDBOX/Onelink_iOS
          USER_TABLE: onelink_dev_users
          PLATFORM_ARN_PROD: arn:aws:sns:!Ref "AWS::Region":!Ref "AWS::AccountId":app/APNS/OnelinkProduction_iOS
  TestLambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm if there is error in TestLambda LATEST version
      #AlarmActions:
      #- Ref: "logical name of an AWS::SNS::Topic resource"
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: '60'
      EvaluationPeriods: '1'
      Threshold: '0'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: FunctionName
        Value: !Ref TestLambda
      - Name: Resource
        Value: !Join [":", [!Ref TestLambda, "live"]]
