AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # Lambda Functions
  TestLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test_lambda
      Handler: test_lambda.lambda_handler
      Runtime: python2.7
      Description: just a test lambda
      Timeout: 15
