AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # Lambda Functions
  TestLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: test_lambda
      Handler: test_lambda.lambda_handler
      Runtime: python2.7
      Description: just a test lambda
      Timeout: 15
      AutoPublishAlias: live
      DeploymentPreference:
       Type: Linear10PercentEvery3Minutes
       
  TestLambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm if there is error in TestLambda LATEST version
      #AlarmActions:
      #- Ref: "logical name of an AWS::SNS::Topic resource"
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: '60'
      EvaluationPeriods: '1'
      Threshold: '0'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: Resource
        Value: !Ref TestLambda
